# @package _group_
conv_module:
  _target_: SQM_discreteness.models.Primary_conv3D
  norm_type: bn
  conv_n_feats: [3, 32, 64]
encoder_module:
  _target_: SQM_discreteness.models.ConvLSTM_block
  in_channels: 64
  hidden_channels: [128, 256]
  #kernel_size: [3, 3]
  #num_layers: 2
  return_all_layers: True
decoder_module:
  _target_: SQM_discreteness.models.FF_classifier
  in_channels: 256
  n_classes: 2
  hidden_channels: 512

arch_id: Net_continuous