# @package _group_
conv_module:
  _target_: SQM_discreteness.models.Primary_conv3D
  norm_type: bn
  conv_n_feats: [3, 32, 64]
encoder_module:
  _target_: SQM_discreteness.models.EncoderLow
  window: 4
  conv_n_feats: [3, 32, 64]
  disc_type: redundant
decoder_module:
  _target_: SQM_discreteness.models.FF_classifier
  in_channels: 256
  n_classes: 5
  hidden_channels: 2048

arch_id: Net_disc_low_redundant