# @package _group_
conv_module:
  _target_: SQM_discreteness.models.Primary_conv3D
  norm_type: bn
  conv_n_feats: [3, 32, 64]
encoder_module:
  _target_: SQM_discreteness.models.EncoderHigh
  window: 4
  conv_n_feats: [3, 32, 64]
  clstm_hidden: [32, 64]
  disc_type: simple
decoder_module:
  _target_: SQM_discreteness.models.FF_classifier
  in_channels: 64
  n_classes: 5
  hidden_channels: 2048

arch_id: Net_disc_high_simple
