file_path: 'dataset.h5'
n_sequences: 4096
sequence_type: 'decode' # recons, decode or sqm
condition: 'V'
n_objects: 1
n_frames: 13
scale: 1.0
n_channels: 3
random_start_pos: True
random_size: True
add_noise: True