# @package _group_
n_epochs: 2
batch_size: 64
val_every_n: 1
train_data_artifact: 'hand_gestures_train_5:latest'
train_data_filename: 'train_hdf55.h5'
is_channels_last: True
task: 'train_hand_gesture_classifier'
separate_val: True
val_data_artifact: 'hand_gestures_val_5:latest'
val_data_filename: 'val_hdf55.h5'
do_train:
  train_conv: True
  train_encoder: True
  train_decoder: True