# @package _group_
n_epochs: 32
batch_size: 32
val_every_n: 1
train_data_artifact: 'videos_decode_V:latest'
train_data_filename: 'dataset.h5'
is_channels_last: False
task: 'train_LR_vernier_classifier'
separate_val: False
do_train:
  train_conv: True
  train_encoder: False
  train_decoder: True