# @package _group_
n_epochs: 50
batch_size: 20
training_data_path: " ls ~/../../work/lpsy/Database/jester20bn/train_hdf55.h5"
task: 'train_hand_gesture_classifier'
do_load:
  load_conv: False
  load_encoder: False
  load_decoder: False
do_train:
  train_conv: True
  train_encoder: True
  train_decoder: True
start_model: 'blank'