# @package _group_
n_epochs: 32
batch_size: 32
train_data_artifact: 'left_right_vernier:latest'
train_data_filename: 'vernier_decode.hdf5'
is_channels_last: False
task: 'train_LR_vernier_classifier'
separate_val: False
do_train:
  train_conv: True
  train_encoder: False
  train_decoder: True